#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_zoom_persist on \
	window_topmost off \
	window_shadow on \
	window_animation_frame_rate 120 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.90 \
	window_opacity off \
	insert_feedback_color 0xffd75f5f \
	active_window_border_color 0xff775759 \
	normal_window_border_color 0xff555555 \
	window_border_width 4 \
	window_border_radius 12 \
	window_border_blur off \
	window_border_hidpi on \
	window_border off \
	split_ratio 0.e0 \
	split_type auto \
	auto_balance off

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 0
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

# modifier for clicking and dragging with mouse (fn alt)
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
#yabai -m mouse_drop_action swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^Bitdefender$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Microsoft To Do$" manage=off
yabai -m rule --add app="^App Store$" manage=off

echo "yabai configuration loaded.."
